# yaml
version: "3.9"

services:
  app:
    build:
      context: .
    container_name: cogito-ai-app
    env_file:
      - .env
    volumes:
      - ./:/app
    working_dir: /app
    command: python main_cli.py
    depends_on:
      - qdrant
      - postgres
    ports:
      - "8000:8000"
    restart: unless-stopped

  qdrant:
    image: crazywillbear/cogito-qdrant:v1
    container_name: cogito-qdrant
    environment:
      - QDRANT__SERVICE__API_KEY=${COGITO_QDRANT_API_KEY}
    ports:
      - "6334:6334"
    restart: unless-stopped

  postgres:
    image: crazywillbear/cogito-postgres-filters:v1
    container_name: cogito-postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
