# yaml
version: "3.9"

services:
  agent:
    build:
      context: .
    container_name: cogito-ai-app
    env_file:
      - .env
    volumes:
      - ./:/app
    working_dir: /app
    command: python main_server.py
    depends_on:
      - qdrant
    ports:
      - "50051:50051"
    restart: unless-stopped

  qdrant:
    image: crazywillbear/cogito-qdrant:v1
    container_name: cogito-qdrant
    environment:
      - QDRANT__SERVICE__API_KEY=${COGITO_QDRANT_API_KEY}
    ports:
      - "6334:6334"
    restart: unless-stopped